# Generated by Django 3.2.25 on 2024-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbaciGG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='block_1_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/about'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='block_2_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/about'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='block_3_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/about'),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='block_4_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/about'),
        ),
    ]
