# Generated by Django 3.2.25 on 2024-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbaciGG', '0002_auto_20240425_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_logo',
            field=models.FileField(blank=True, null=True, upload_to='images/clients'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/services'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.FileField(upload_to='images/site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_footer_logo',
            field=models.FileField(upload_to='images/site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_header_logo',
            field=models.FileField(upload_to='images/site'),
        ),
    ]
