# Generated by Django 3.2.25 on 2024-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbaciGG', '0003_auto_20240425_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='images/site'),
        ),
    ]
