# Generated by Django 3.2.25 on 2024-06-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbaciGG', '0004_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_detail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
